# Generated by Django 4.1.6 on 2023-04-06 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_quiz_quizquestions_coursequiz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='detail',
            field=models.TextField(),
        ),
    ]
