# Generated by Django 4.1.6 on 2023-04-06 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_quiz_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizquestions',
            name='questions',
        ),
    ]
