# Generated by Django 4.1.6 on 2023-04-06 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_remove_quizquestions_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestions',
            name='question',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
