# Generated by Django 4.1.6 on 2023-04-10 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_student_otp_digit_student_verify_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='otp_digit',
        ),
        migrations.RemoveField(
            model_name='student',
            name='verify_status',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='otp_digit',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='verify_status',
        ),
    ]
